Added Rubocop formatter
bigbinary/neeto-filters-backend pull request #11
Opened 2022-04-13 05:27 UTC by AbhayVAshokan

Fixes #10
- Added `rubocop` and `rubocop-rails` gems as development dependencies.
- Corrected all the offenses raised by the rubocop rules.

@Amaljith-K _a please have a look.

2022-04-14 07:07 UTC, Amaljith-K commented
Please include a rubocop pre-commit validation as well.
https://vimeo.com/699329319/3703845773

@AbhayVAshokan _a

2022-04-14 13:19 UTC, AbhayVAshokan commented
@Amaljith-K _a please review.

2022-04-18 07:55 UTC, Amaljith-K requested changes
@AbhayVAshokan _a

2022-04-18 07:55 UTC, Amaljith-K commented on bin/setup
> +  system!("cp -R #{APP_ROOT}/.github/hooks #{APP_ROOT}/.git")
Add a `puts "Done"` to indicate all steps were successfully completed.
Currenly the logging output feels incomplete
![image](https://user-images.githubusercontent.com/85148587/163769585-08d50d4c-aba8-4c71-8787-025501fa5161.png)

2022-04-18 07:55 UTC, Amaljith-K commented on bin/setup
> +  system!("cp -R #{APP_ROOT}/.github/hooks #{APP_ROOT}/.git")
Also perform `system!("chmod +x #{APP_ROOT}/.git/*")` to ensure execution permissions are properly set.

2022-04-18 07:55 UTC, Amaljith-K commented on bin/setup
> +  system!("cp -R #{APP_ROOT}/.github/hooks #{APP_ROOT}/.git")
It is best to create a link instead of copying the file. 
`ln -f #{APP_ROOT}/.github/hooks/* #{APP_ROOT}/.git/hooks/`
So when any new changes are introduced to the hooks, we don't need to run `bin/setup` every time

2022-04-18 07:55 UTC, Amaljith-K commented on .github/hooks/pre-commit
> +staged_files=$(git diff-index --staged --name-only --diff-filter=ACMR $against)
Is there any reason to prefer `git diff-index` over `git diff`?
`git diff-index` won't work correctly when doing `git commit -am "message"` instead of manually adding all files to staging and then committing.

2022-04-18 10:58 UTC, AbhayVAshokan commented
@Amaljith-K _a please review.

2022-04-19 04:37 UTC, Amaljith-K approved these changes
LGTM

2022-04-19 04:37 UTC, merged